name: prod
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - nodejs
  - pandas
  - playwright
  - lxml
  - python=3.10
  - scikit-learn
  - scikit-plot
  - seaborn
  - matplotlib
  - plotly
  - pillow
  - tqdm
  - xgboost
  - gdown
  - psycopg2
  - pytorch
  - geopy
  - pip
  - pip:
      - python-dotenv
      - ydata-profiling
      - scrapy
      - scrapy-playwright
      - geopy
      - selenium
      - webdriver_manager
      - deep-translator
      - psycopg2-binary
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.37.2
      - sentence-transformers==2.6.1
      - streamlit
      - numpy==1.26.4

