name: prod
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - nodejs
  - pandas
  - playwright
  - lxml
  - python=3.10
  - scikit-learn
  - scikit-plot
  - seaborn
  - pip
  - pip:
      - python-dotenv
      - ydata-profiling
      - scrapy
      - scrapy-playwright
      - geopy
      - selenium
      - webdriver_manager
